#! /bin/sh
# aws-host-fingerprints (Bourne shell script) -- 

if [ -z "$1" ] ; then
  echo "Usage: aws-host-fingerprints <instance-id>" >&2
  exit 1
fi

aws ec2 --output=text get-console-output --instance-id=$1 | \
  sed -n '/^ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----/,/^ec2: -----END SSH HOST KEY FINGERPRINTS-----/p'
