#! /bin/sh
# aws-host-fingerprints (Bourne shell script) -- 

self=aws-host-fingerprints

if [ -z "$1" ] ; then
  echo "Usage: $self <instance-id>" >&2
  exit 1
fi

aws ec2 --output=text get-console-output --instance-id=$1 | \
  sed -n '/^ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----/,/^ec2: -----END SSH HOST KEY FINGERPRINTS-----/p' | \
  tee /tmp/aws-host-fingerprints_$$

# If there is nothing in the file, throw an error
if [ ! -s /tmp/aws-host-fingerprints_$$ ] ; then
  echo "${self}: Warning: console output for instance $1 does not contain host fingerprints" >&2
  exit 2
fi
