#! /bin/sh
# aws-iterate (Bourne shell script) -- runs a command in each AP and US region

for region in us-east-1 ap-northeast-1 us-west-2 us-west-1 ap-southeast-1 ap-southeast-2 ; do
  echo $region:
  aws --region=$region "$@"
done
