#! /bin/sh
# c_dump (Bourne shell script) -- Dumps info about PEM-format X.509 certificate(s)
#
# Tolerates failure to open a file by not showing anything other than the
# openssl error.
# Accepts "-" as an argument to read that cert from stdin.
# By default, reads a cert from stdin.
#
# Uses a pager per file

if [ $# -eq 0 ] ; then
  set -- -
fi

# Similar to "-nameopt RFC2253" but with semicolons
OPTS="-nameopt esc_2253,esc_ctrl,esc_msb,utf8,dump_nostr,dump_unknown,dump_der,sep_semi_plus_space,dn_rev,sname"

for file do
  if [ "$file" = - ] ; then
    info="$(openssl x509 -text $OPTS -noout)"
  else
    if ! info="$(openssl x509 -text $OPTS -noout -in "$file")"
    then
      continue
    fi
  fi
  echo "$info" | ${PAGER:-less}
done
