#! /bin/sh
# c_issuer (Bourne shell script) -- Shows issuer of PEM-format X.509 certificate(s)
#
# Works similar to c_issuer from the 'openssl' package, but without bugs
#
# Tolerates failure to open a file by not showing anything other than the
# openssl error.
# Accepts "-" as an argument to read that cert from stdin.
# By default, reads a cert from stdin.

if [ $# -eq 0 ] ; then
  set -- -
fi

# Similar to "-nameopt RFC2253" but with semicolons and without dn_rev
OPTS="-nameopt esc_2253,esc_ctrl,esc_msb,utf8,dump_nostr,dump_unknown,dump_der,sep_semi_plus_space,sname"

for file do
  if [ "$file" = - ] ; then
    info="$(openssl x509 -issuer $OPTS -noout)"
  else
    if ! info="$(openssl x509 -issuer $OPTS -noout -in "$file")"
    then
      continue
    fi
  fi
  printf '%s\t%s\n' "$file" "$info"
done
