#! /bin/sh
# current-song (Bourne shell script) -- scrobbles to STDOUT

if [ "$MUSIC_PLAYER" = audacious ] ; then
  audtool current-song
else
  echo 'current-song: please set MUSIC_PLAYER environment variable' >&2
  exit 3
fi | sed -e 's/\([^~]*\)~\([^~]*\)~ABSOLUTERADIOIR.*/\1 - \2/'
