#! /bin/sh
# dump-crontabs (Bourne shell script) -- 

DIR=/var/spool/cron/crontabs
OUTPUT_DIR=tmp/$(date +%F)

set -e
mkdir $OUTPUT_DIR

for user in $(sudo ls /var/spool/cron/crontabs) ; do
  # Only copy the file if it contains something
  if sudo [ -s $DIR/$user ] ; then
    sudo crontab -u $user -l > $OUTPUT_DIR/$user.cron
  fi
done
