#! /bin/sh
# fix_vimfile  (Bourne shell script) -- Strips out everything from a .vim file except buffers

sed -i.bak '/^\(tab\|edit\|l\?cd \|wincmd\|badd \|split\|vsplit\|[0-9]*wincmd \|if bufexists\|normal! zt$\|[[:digit:]]\+$\|normal! [[:digit:]]\+|$\)/ !d
/^wincmd _/d
## s/^edit/spl/' "$@"
