#! /bin/bash
# get (BASH script) -- downloads a PDF into the reading dir

if [ -d ~/Reading ] ; then
  reading_dir=~/Reading
else
  reading_dir=~/Desktop/Reading
fi

if [[ "$1" != http* && "$1" != ftp* && "$1" != www* && -d "$reading_dir/$1" ]] ; then
  dl_dir=$reading_dir/$1
  shift
fi

wget -N -P "$dl_dir" "$@"
