#! /bin/sh
# minicombine (Bourne shell script) -- Merge two files and provide git(1) style output
#
# Based a Super User answer https://superuser.com/a/1541906/197866
# by https://superuser.com/users/337631/davidpostill


SELF=minicombine

if [ $# -lt 2 ] ; then
  ## echo "$SELF: Error: " >&2
  echo "Usage: $SELF <file1> <file2>" >&2
  exit 1
fi

diff --old-line-format='%L' --new-line-format='%L' "$@"
     ## --unchanged-group-format="%L" \
