#! /bin/csh -f
# pdf2txt (C shell script) -- Extracts the text from a PDF file

if ($#argv < 1) then
  sh -c 'echo pdf2txt: no filename supplied 1>&2'
  exit 1
endif
set file = /tmp/pdf$$.ipe
if { pdftoipe $1:q $file } then
  sed -e '/^<imag/,/<\/image/d' -e '/<--/d' $file | xsltproc ~/bin/ipe2txt.xsl -
endif
