#! /bin/sh
# r_dump (Bourne shell script) -- Dumps info about PEM-format X.509 certificate request(s)
#
# Tolerates failure to open a file by not showing anything other than the
# openssl error.
# Accepts "-" as an argument to read that cert from stdin.
# By default, reads a cert from stdin.

if [ $# -eq 0 ] ; then
  set -- -
fi

# Similar to "-nameopt RFC2253" but with semicolons
OPTS="-nameopt esc_2253,esc_ctrl,esc_msb,utf8,dump_nostr,dump_unknown,dump_der,sep_semi_plus_space,dn_rev,sname"

for file do
  if [ -n "$prevfile" ] ; then
    echo "--------"
  fi
  prevfile="$file"   # Do this here to avoid missing out in case of openssl error

  if [ "$file" = - ] ; then
    info="$(openssl req -text $OPTS -noout)"
  else
    if ! info="$(openssl req -text $OPTS -noout -in "$file")"
    then
      continue
    fi
  fi
  echo "$file"
  echo "$info"
done
