#! /bin/sh
# readdoc (Bourne shell script) -- Read a .doc or .docx file in a text pager
#
# Uses a 4-space indent on each line plus a 2-space first-line indent per
# paragraph.  Uses 65 for the text width; set $TEXT_WIDTH (an environment
# variable) to alter.

docx2txt "$1" - |
  sed -e 'a\
' -e '/./ s/^/  /' |
  fold -sw ${TEXT_WIDTH-65} |
  sed  -e '/./ s/^/    /' |
  ${PAGER-less}
