#! /bin/sh
# s_dump_smtp (Bourne shell script) -- Connects to an SMTP server, invokes STARTTLS and shows info about the X.509 certificate

# Similar to "-nameopt RFC2253" but with semicolons and without dn_rev
OPTS="-nameopt esc_2253,esc_ctrl,esc_msb,utf8,dump_nostr,dump_unknown,dump_der,sep_semi_plus_space,sname"
SELF=$(basename "$0")

if [ $# -ne 1 ] ; then
  echo "Usage: s_dump_smtp <servername>" >&2
  exit 1
fi

if [ -z "$SSL_PATH" ] ; then
  echo $SELF: 'ERROR: $SSL_PATH not set' >&2
  exit 2
fi

openssl s_client -connect $1:587 -starttls smtp -tls1 -CApath $SSL_PATH/certs/ < /dev/null |
  openssl x509 -text $OPTS -noout |
  ${PAGER:-less}
