#! /bin/sh
# s_dump_ldap (Bourne shell script) -- Connects to an SSL LDAP server and shows info about the X.509 certificate for a given domain
#
# Version: 1.1
# Copyright: (c) 2019 Alastair Irvine <alastair@plug.org.au>
# Keywords: openssl, SSL, secure certificate
# Licence: This file is released under the GNU General Public License
#
# Uses "Server Name Indication" (SNI)

# Similar to "-nameopt RFC2253" but with semicolons and without dn_rev
OPTS="-nameopt esc_2253,esc_ctrl,esc_msb,utf8,dump_nostr,dump_unknown,dump_der,sep_semi_plus_space,sname"
SELF=$(basename "$0")

if [ "$1" = -P ] ; then
  PORT=$2
  shift
  shift
fi

if [ $# -lt 1 -o $# -gt 3 ] ; then
  echo "Usage: $SELF [ -P <port> ] <servername> [ <sitename> ] [ <opts> ]" >&2
  exit 1
fi

if [ -z "$SSL_PATH" ] ; then
  if [ -d /etc/pki/tls ] ; then
    SSL_PATH=/etc/pki/tls
  else
    SSL_PATH=/etc/ssl
  fi
fi

openssl s_client -connect $1:${PORT-636} -servername ${2:-$1} -${3:-tls1} -CApath $SSL_PATH/certs/ < /dev/null |
  openssl x509 -text $OPTS -noout |
  ${PAGER:-less}
