#! /bin/sh
# s_dump_http (Bourne shell script) -- Connects to an SSL HTTP server and shows info about the X.509 certificate for a given domain

# Similar to "-nameopt RFC2253" but with semicolons
OPTS="-nameopt esc_2253,esc_ctrl,esc_msb,utf8,dump_nostr,dump_unknown,dump_der,sep_semi_plus_space,dn_rev,sname"
SELF=$(basename "$0")

if [ $# -lt 1 -o $# -gt 3 ] ; then
  echo "Usage:  <servername> [ <sitename> ] [ <opts> ]" >&2
  exit 1
fi

if [ -z "$SSL_PATH" ] ; then
  echo $SELF: 'ERROR: $SSL_PATH not set' >&2
  exit 2
fi

openssl s_client -connect $1:443 -servername ${2:-$1} -tls1 -CApath $SSL_PATH/certs/ < /dev/null |
  openssl x509 -text $OPTS -noout |
  ${PAGER:-less}
