#! /bin/sh
# s_verify_imap (Bourne shell script) -- Connects to an IMAP server, invokes STARTTLS and verifies the X.509 certificate

openssl s_client -connect $1:143 -starttls imap -${2:-tls1} -verify 20 -CApath $SSL_PATH/certs/ < /dev/null |
  sed "/^-----BEGIN CERTIFICATE-----/,/^-----END CERTIFICATE-----/d" |
  ${PAGER:-less}
