#! /bin/sh
# s_verify_http (Bourne shell script) -- Connects to an SSL HTTP server and verifies the X.509 certificate for a given domain
#
# Note: Verifies the chain but won't actually compare the CN of the returned
# cert agains the server name

openssl s_client -connect $1:443 -servername ${2:-$1} -${3:-tls1} -verify 20 -CApath $SSL_PATH/certs/ < /dev/null |
  sed "/^-----BEGIN CERTIFICATE-----/,/^-----END CERTIFICATE-----/d" |
  ${PAGER:-less}
