#! /bin/sh
# s_verify_pop3s (Bourne shell script) -- Connects to an SSL POP3 server and verifies the X.509 certificate
#
# Version: 1.1
# Copyright: (c) 2019 Alastair Irvine <alastair@plug.org.au>
# Keywords: openssl, SSL, TLS, secure certificate
# Licence: This file is released under the GNU General Public License v2

SELF=$(basename "$0")

if [ "$1" = -P ] ; then
  PORT=$2
  shift
  shift
fi

if [ $# -lt 1 -o $# -gt 3 ] ; then
  echo "Usage: $SELF [ -P <port> ] <servername> [ <opts> ]" >&2
  exit 1
fi

if [ -z "$SSL_PATH" ] ; then
  if [ -d /etc/pki/tls ] ; then
    SSL_PATH=/etc/pki/tls
  else
    SSL_PATH=/etc/ssl
  fi
fi

openssl s_client -connect $1:${PORT-995} -${2:-tls1} -verify 20 -CApath $SSL_PATH/certs/ < /dev/null |
  sed "/^-----BEGIN CERTIFICATE-----/,/^-----END CERTIFICATE-----/d" |
  ${PAGER:-less}
