#! /bin/sh
# s_verify_imaps (Bourne shell script) -- Connects to an SSL IMAP server and verifies the X.509 certificate

openssl s_client -connect $1:993 -${2:-tls1} -verify 20 -CApath $SSL_PATH/certs/ < /dev/null |
  sed "/^-----BEGIN CERTIFICATE-----/,/^-----END CERTIFICATE-----/d" |
  ${PAGER:-less}
