#! /bin/sh
# update (Bourne shell script) -- revision control swiss army knife
#
# TO-DO: pass git options?

SELF=$(basename "$0")

fn()
{
  set -e

  if [ -d .git ] ; then
    git pull
  elif [ -d .svn ] ; then
    svn update
  else
    echo "$SELF: WARNING: no revision control directory found in $PWD" >&2
  fi
}


# *** MAINLINE ***
if [ -n "$1" ] ; then
  # Process each argument by recursively calling this script
  for dir do
    if [ -d "$dir" ] ; then
      (set -e ; cd "$dir" ; "$0")
    else
      echo "$SELF: ERROR: '$dir' isn't a directory" >&2
    fi
  done
else
  # No arguments so just get the job done
  fn
fi
