#! /usr/bin/python3
# vim: set fileencoding=utf-8 tabstop=4 shiftwidth=4 :
# wsort (Python script) -- Sorts words on each line
#
# Version:   
# Copyright: (c)2021 Alastair Irvine <alastair@plug.org.au>
# Keywords:  
# Notice:    
# Licence:   This file is released under the GNU General Public License
#
'''Description:
  
Usage: 
Options:
  
'''
# Licence details:
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or (at
#     your option) any later version.
#
#     See http://www.gnu.org/licenses/gpl-2.0.html for more information.
#
#     You can find the complete text of the GPLv2 in the file
#     /usr/share/common-licenses/GPL-2 on Debian systems.
#     Or see the file COPYING in the same directory as this program.
#
#
# TO-DO:

import sys


self="wsort"
allowed_options='hd'
allowed_long_options=['help']


# *** CLASSES ***

# *** FUNCTIONS ***
def show_help(dest=sys.stdout):
    print(__doc__.rstrip(), file=dest)


def report_error(msg):
    print(self + ": Error: " + msg, file=sys.stderr)


def report_warning(msg):
    print(self + ": Warning: " + msg, file=sys.stderr)


def report_notice(msg):
    print(self + ": Notice: " + msg, file=sys.stderr)


# For cmdline args, use argv[1:].  argv[0] is program filename.
def main(argv):
    """Acts like main() in a C program.  Return value is used as program exit code."""

    # == sanity checking ==


    # == preparation ==
    src = sys.stdin
    sep = " "


    # == processing ==
    for line in src.readlines():
        print(sep.join(sorted(line.rstrip("\n").split(sep))))


    return 0


# *** MAINLINE ***
if __name__ == '__main__':
    sys.exit(main(sys.argv))
